---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by momo.
--- DateTime: 2019/11/10 上午11:29
---



label = Label()
label:setGravity(Gravity.CENTER)
label:text("测试")

local contentView = View():width(MeasurementType.MATCH_PARENT):height(MeasurementType.MATCH_PARENT):setGravity(Gravity.CENTER_HORIZONTAL)
prevSelectedView = require("MessagePagerView"):new()

contentView:addView(prevSelectedView:rootView())

window:addView(contentView)

--ibutton = Label()
--ibutton:text("c")
--ibutton:setGravity(Gravity.TOP)
--ibutton.onClick(function()
--    local MLToast = require("LuaComponent.MLToast.MLToast")
--    MLToast("你好啊！！！", 2, window, -30)
--end)
--window:addView(ibutton)
